In [4]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Answer 1
array_3x3 = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", array_3x3)
print("Transposed Array:\n", array_3x3.T)

Original Array:
 [[ 6 93  9]
 [34 34 24]
 [10 16 67]]
Transposed Array:
 [[ 6 34 10]
 [93 34 16]
 [ 9 24 67]]


In [3]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np

# Answer 2
array_1d = np.arange(10)
reshaped_2x5 = array_1d.reshape(2, 5)
reshaped_5x2 = array_1d.reshape(5, 2)
print("2x5 Array:\n", reshaped_2x5)
print("5x2 Array:\n", reshaped_5x2)

2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Answer 3
array_4x4 = np.random.random((4, 4))
bordered_array = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("Bordered Array:\n", bordered_array)

Bordered Array:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.10456012 0.91842588 0.68453846 0.73390008 0.        ]
 [0.         0.47305645 0.6097004  0.05234916 0.78037897 0.        ]
 [0.         0.30345793 0.55394286 0.76030589 0.80951091 0.        ]
 [0.         0.48068997 0.59800174 0.51507815 0.4343486  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

# Answer 4
array_step = np.arange(10, 61, 5)
print("Array with Step 5:\n", array_step)

Array with Step 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [7]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

# Answer 5
strings = np.array(['python', 'numpy', 'pandas'])
uppercase = np.char.upper(strings)
lowercase = np.char.lower(strings)
title_case = np.char.title(strings)
print("Uppercase:\n", uppercase)
print("Lowercase:\n", lowercase)
print("Title Case:\n", title_case)

Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Title Case:
 ['Python' 'Numpy' 'Pandas']


In [8]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

# Answer 6
words = np.array(['hello', 'world'])
spaced_words = np.char.join(' ', np.array(list(words)))
print("Words with Spaces:\n", spaced_words)

Words with Spaces:
 ['h e l l o' 'w o r l d']


In [9]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

# Answer 7
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [10]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

# Answer 8
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [11]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
from sympy import isprime

# Answer 9
random_integers = np.random.randint(0, 1000, size=100)
primes = [num for num in random_integers if isprime(num)]
print("Prime Numbers:\n", primes)

Prime Numbers:
 [601, 919, 599, 151, 233, 599, 269, 29, 449, 293, 347, 181, 223, 227, 37, 823]


In [13]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

# Answer 10
temperatures = np.random.randint(0, 35, size=30)
weekly_averages = temperatures.reshape(-1, 6).mean(axis=1)
print("Weekly Averages:\n", weekly_averages)

Weekly Averages:
 [21.5        22.         12.5        20.83333333 18.5       ]
